=== nomyrlabajowork/batch5sample/Documents/docs/employees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- declare prefix : 'xs' -->
<!-- targetNamespace - link to XML -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.ssglobal.org/training/employees" 
	xmlns:tns="http://www.ssglobal.org/training/employees" 
	elementFormDefault="qualified">
	
	<xs:group name="namesGrp">
		<xs:choice>
			<xs:element name="firstname" >
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="4"/>	
						<xs:whiteSpace value="collapse"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="lastname">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="3"/>
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:choice>
	</xs:group>
		
	<xs:group name="secretDetailsGrp">
		<xs:choice>
			<xs:element name="salary" default="10000.00">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="9000.00"/>
						<xs:maxInclusive value="500000.00"/>
						<xs:fractionDigits value="2"/><!-- for decimals only -->
						
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="address">
				<xs:complexType mixed="true">
					<xs:all>
					<!-- allowed occurrence is min=1/0, max=1 -->
						<xs:element name="city" type="xs:string"/>
						<xs:element name="country" minOccurs="0" maxOccurs="1">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<!-- <xs:pattern value="[A-Z][A-Z][A-Z]"/> -->
									<!-- <xs:pattern value="[A-Z]{2}|[A-Z]{3}"/> -->
									<xs:pattern value="[A-Z]+"/>
									<xs:minLength value="2"/>
									<xs:maxLength value="3"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="zip">
							<xs:simpleType>
								<xs:restriction base="xs:int">
									<xs:totalDigits value="4"/>
									<xs:enumeration value="1443"/>
									<xs:enumeration value="2020"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
					</xs:all>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	
	<xs:element name="employees">
		<xs:complexType>
		
			<xs:sequence>
				<xs:element name="employee" minOccurs="2" maxOccurs="3">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" default="100">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="100"/>
										<xs:maxExclusive value="500"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<!-- reference back -->
							<xs:group ref="tns:namesGrp"/>
							<xs:element name="age" default="18">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:integer">
											<xs:attribute name="classification" type="xs:string"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							
							<!-- reference back -->
							<xs:group ref="tns:secretDetailsGrp" minOccurs="0" maxOccurs="1"/>
							<!-- empty element -->
							<xs:element name="company">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string"/>
									<xs:attribute name="years" type="xs:integer"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="pk" type="xs:integer" default="10"/>
						<xs:attribute name="pos" type="xs:string" default="manager"/>
						<xs:attribute name="outbound" type="xs:boolean" use="optional"/>
						<xs:attribute name="gender" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="male"/>
									<xs:enumeration value="female"/>
									<xs:enumeration value="non-binary"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nomyrlabajowork/batch5sample/Documents/docs/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- DOCTYPE employees SYSTEM "employees.dtd" --> <!-- for DTD only -->
<employees  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xmlns="http://www.ssglobal.org/training/employees"
			xsi:schemaLocation="http://www.ssglobal.org/training/employees employees.xsd">
		<employee gender="male">
			<id></id>
			<firstname>Juan</firstname>
			<age classification="teen" ></age>
			<salary></salary>
			<company/>
		</employee>
		<employee pk="1" pos="manager" outbound="true" gender="female">
			<id></id>
			<firstname>Mari</firstname>
			<age classification="senior">60</age>
			<salary>90000.19</salary>
			<company/>
		</employee>
		<employee pk="2" pos="manager" gender="non-binary">
			<id>499</id>
			<lastname>Cruz</lastname>
			<age classification="adult">35</age>
			<address>Batangas
				<country>PH</country>
				<zip>2020</zip>
				<city>Lipa</city>
			</address>
			<company name="77Global" years="25"/>
		</employee>
</employees>
